CREATE TABLE CUSTOMER (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CUSTOMERNAME VARCHAR(20) ,
    SURNAME VARCHAR(30) ,
    PHONENUMBER VARCHAR(15) ,
    ADDRESS VARCHAR(50)
 );